[package]
name = "flex-viewer"
version = "0.1.0"
authors = ["Golodnyi <ochen@golodnyi.ru>"]

[dependencies]
flex = { path = "src/flex/src", version = "*" }
reader = { path = "src/reader/src", version = "*" }
html = { path = "src/html/src", version = "*" }