[package]
name = "flex-viewer"
version = "0.1.0"
authors = ["Golodnyi <ochen@golodnyi.ru>"]

[dependencies]
bitreader = "0.3.1"
serde_json = "1.0"
serde_derive = "1.0.59"
serde = "1.0.59"
byteorder = "1.2.3"